# Generated by Django 4.0.3 on 2022-03-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Developer'), (2, 'Manager'), (3, 'Admin')], default=1, max_length=9),
        ),
    ]
