# Generated by Django 4.0.3 on 2022-03-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Developer', max_length=9),
        ),
    ]
