# Generated by Django 4.0.3 on 2022-03-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0004_project_ticket_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
