# Generated by Django 4.0.3 on 2022-03-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0005_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trackersite.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
