# Generated by Django 4.0.3 on 2022-03-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0006_ticket_project_alter_ticket_ongoing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
    ]
