# Generated by Django 4.0.1 on 2022-04-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0011_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='types',
            field=models.CharField(choices=[('New', 'Bugs'), ('Open', 'Feat'), ('Resolved', 'Comm')], default='New', max_length=11),
        ),
    ]
