# Generated by Django 4.0.1 on 2022-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0012_ticket_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='types',
            field=models.CharField(choices=[('Bug/Errors', 'Bugs'), ('Features', 'Feat'), ('General Comments', 'Comm')], default='Bug/Errors', max_length=16),
        ),
    ]
