# Generated by Django 4.0.1 on 2022-04-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0013_alter_ticket_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='types',
            new_name='type',
        ),
    ]
