# Generated by Django 4.0.1 on 2022-04-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0016_project_creator_project_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not'), ('In Progress', 'Prgrs'), ('Complete', 'Cmplte')], default='Not Started', max_length=11),
        ),
    ]
