# Generated by Django 4.0.1 on 2022-04-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0019_alter_project_creator_alter_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
