# Generated by Django 4.0.1 on 2022-04-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0021_alter_comment_timestamp_alter_project_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='value_field',
            field=models.CharField(max_length=9),
        ),
    ]
