# Generated by Django 4.0.3 on 2022-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0025_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/covers/pfp1.jpg', upload_to='media/covers'),
        ),
    ]
