# Generated by Django 4.0.3 on 2022-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0026_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='covers/pfp1.jpg', upload_to='covers'),
        ),
    ]
