# Generated by Django 4.0.3 on 2022-04-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackersite', '0027_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
